### ISSUE TITLE
Add template_uri() helper function

### ISSUE THREAD

**Issue by vinkla** [wordplate/framework#40]
Instead of always having to write the entire path with the `get_template_directory_uri()` function we could create a helper function to simplify this process.

Before:
```php
<link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/assets/styles/app.css">
```
After:
```php
<link rel="stylesheet" href="<?php echo template_uri('assets/styles/app.css'); ?>">
```

**Comment by vinkla** [comment]
Maybe we should name this method `asset()` instead to be more in line with Laravel?

@puredazzle what is your opinion on this?

**Comment by puredazzle** [comment]
@vinkla `assets()` could be good because from my experience this is only used for items inside the assets folder. Then I guess it should be 

```
<link rel="stylesheet" href="<?php echo assets('styles/app.css'); ?>">
```

**Comment by vinkla** [comment]
We decided to go with `asset()` 👍
