### ISSUE TITLE
MU plugins are removed from active_plugins options because of relative path (Invalid plugin path)

### ISSUE THREAD

**Issue by nreynis** [wordplate/framework#86]
The `PluginLoader` add all mu plugins to the `active_plugins` option here:
https://github.com/wordplate/framework/blob/master/src/PluginLoader.php#L132

This generate a relative url of the form:
```
active_plugins
a:6:{i:0;s:61:
	"../mu-plugins/jwt-authentication-for-wp-rest-api/jwt-auth.php";i:1;s:29:
	"../mu-plugins/plate/plate.php";i:2;s:38:
	"../mu-plugins/wordpress-seo/wp-seo.php";i:3;s:55:
	"../mu-plugins/wp-rest-yoast-meta/wp-rest-yoast-meta.php";i:4;s:51:
	"all-in-one-wp-security-and-firewall/wp-security.php";i:5;s:29:
	"hide-updates/hide-updates.php";}

active_mu_plugins
a:4:{i:0;s:47:
	"jwt-authentication-for-wp-rest-api/jwt-auth.php";i:1;s:15:
	"plate/plate.php";i:2;s:41:
	"wp-rest-yoast-meta/wp-rest-yoast-meta.php";i:3;s:24:
	"wordpress-seo/wp-seo.php";}
```

Thoses will the generate `Invalid plugin path` errors and will be removed by wordpress when the plugin administration page is viewed. The stacktrace is:

1 - View admin page: https://github.com/WordPress/WordPress/blob/master/wp-admin/plugins.php#L481
2 - Loop through all plugins: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/plugin.php#L1044
3 - Validate individual plugin: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/plugin.php#L1064
4 - Detect potential path traversal attack: https://github.com/WordPress/WordPress/blob/master/wp-includes/functions.php#L4901
5 - Return Invalid plugin path: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/plugin.php#L1065
6 - Desactivate plugin: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/plugin.php#L1047
7 - Print error to end user: https://github.com/WordPress/WordPress/blob/master/wp-admin/plugins.php#L483

**Comment by nreynis** [comment]
Also I fail to understand what's the point of having a relative path here. The function says that it's intended to make `is_plugin_active` works, which is a good thing: a lot of plugins check for their install requirements like that.

But `is_plugin_active` does not resolve paths it assume all plugins paths are INSIDE the plugin directory:
https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/plugin.php#L508

Which means that when a plugin will check for a dependencies, ex:
```
public function check_requirements() {
        if ( ! is_plugin_active( 'wordpress-seo-premium/wp-seo-premium.php' ) && ! is_plugin_active( 'wordpress-seo/wp-seo.php' ) ) {
              // ...
        }
}
```
This will never detect that the dependencies are installed.

**Comment by vinkla** [comment]
Thanks for digging into this @nreynis! I'll redirect this question to @tditlu and @fiskhandlarn who knows the ins-n-outs of the plugin loader. Also, we'll happily look at any pull request you send our way!

**Comment by nreynis** [comment]
I don't have any idea of how this could be made to work:
- nesting mu-plugins into plugins is a dead-end. It causes more problems than it solves
- creating "dummy" placeholder plugins in the regular plugin folder to trick wordpress seems to work at first, but as soon as you make any action on any plugin they are all removed from active_plugins

**Comment by fiskhandlarn** [comment]
@nreynis I can confirm this. Vanilla plugins aren't activated when clicking "Activate" in `wordpress/wp-admin/plugins.php`. AFAIK this doesn't happens due to PluginLoader::optionActivePlugins(), but rather in preUpdateOptionActivePlugins() (where plugins are compared against the `active_mu_plugins` option).

@tditlu @vinkla What is the purpose of `add_filter('pre_update_option_active_plugins', [$this, 'preUpdateOptionActivePlugins']);`? This doesn't seem to be called when mu-plugins are activated, but only when manually activating vanilla plugins in wp-admin.

**Comment by vinkla** [comment]
@nreynis @fiskhandlarn I know it has almost been a year. Where do we go from here?

**Comment by nreynis** [comment]
Hi @vinkla, I never solved the issue on my side. The error is non blocking, so the product shipped with it. I have since changed company and haven't the original code setup to do any testing.

**Comment by fiskhandlarn** [comment]
@vinkla I think I forgot about this after asking you and @tditlu X)

**Comment by vinkla** [comment]
Thanks for getting back! I'll go ahead and close this. If anyone else finds this in the future. Please submit a pull request.
